server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_system
    username: root
    password: 123456
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml # 如果使用 XML 映射文件
  type-aliases-package: com.itmang.pojo.entity # 实体类所在的包
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名


jwt:
  admin-secret-key: itmang
  admin-ttl: 7200000
  admin-token-name: token

#日志输出
logging:
  level:
    com:
      itmang:
        mapper: debug
        service: info
        controller: info

springdoc:
  api-docs:
    #是否开启文档功能
    enabled: true
    #swagger后端文档请求地址
    path: /api-docs
  swagger-ui:
    #自定义前端请求路径
    path: /swagger-ui
  #包扫描的路径,可定义多个扫描路径，如果是多个则用逗号隔开
  packages-to-scan: com.itmang.controller

